package com.complai.coldsales.models.pipeline.email;

import java.util.List;

/**
 * Represents subject line options generated by the pipeline.
 * Part of the email pipeline results.
 */
public class SubjectOptions {
    private final String primary;
    private final List<String> alternatives;
    private final int predictedOpenRate;
    private final String strategy;
    
    public SubjectOptions(String primary, List<String> alternatives, 
                         int predictedOpenRate, String strategy) {
        this.primary = primary;
        this.alternatives = alternatives;
        this.predictedOpenRate = predictedOpenRate;
        this.strategy = strategy;
    }
    
    public String getPrimary() {
        return primary;
    }
    
    public List<String> getAlternatives() {
        return alternatives;
    }
    
    public int getPredictedOpenRate() {
        return predictedOpenRate;
    }
    
    public String getStrategy() {
        return strategy;
    }
    
    @Override
    public String toString() {
        return "SubjectOptions{" +
                "primary='" + primary + '\'' +
                ", alternatives=" + (alternatives != null ? alternatives.size() + " options" : "null") +
                ", predictedOpenRate=" + predictedOpenRate +
                ", strategy='" + strategy + '\'' +
                '}';
    }
}

